# Generated by Django 2.0.6 on 2018-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_num', models.IntegerField(max_length=3)),
                ('cam_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
