# Generated by Django 2.0.6 on 2018-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_num',
            field=models.IntegerField(),
        ),
    ]
