# Generated by Django 2.0.6 on 2018-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0002_auto_20180615_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_id', models.IntegerField()),
                ('gps_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
