# Generated by Django 2.0.6 on 2018-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0004_auto_20180627_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_ip',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cam_password',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cam_username',
            field=models.CharField(max_length=35),
        ),
    ]
