# Generated by Django 2.0.6 on 2018-07-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0005_auto_20180628_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
