# Generated by Django 2.0.6 on 2018-07-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0006_camera_cam_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_port',
            field=models.IntegerField(default=8000),
            preserve_default=False,
        ),
    ]
