# Generated by Django 2.0.6 on 2018-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senforce', '0007_camera_cam_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=10)),
                ('user_lname', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=25)),
                ('user_organization', models.CharField(max_length=25)),
            ],
        ),
    ]
